config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'admin' => 'static_pages#admin'
  get 'report' => 'static_pages#report'
  post 'submit' => 'static_pages#submit'
  get 'news_items' => 'static_pages#news_items'
  get 'actions' => 'static_pages#actions'
  get 'strength' => 'static_pages#strength'
  get 'gravity' => 'static_pages#gravity'
  get 'level' => 'static_pages#level'
  get 'showmode' => 'static_pages#show_mode'


  get 'login' => 'sessions#new'
  get 'session' => 'sessions#index'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'signup' => 'users#new'
  resources :users
  get 'achievement_levels' => 'users#achievement_levels'

  resources :account_activations, only: [:edit]

  get 'build_orders/finished' => 'build_orders#finished'
  get 'build_orders/get_orders/:id' => 'build_orders#get_orders'
  resources :build_orders, only: [:new, :create, :index, :show]

  resources :tower, only: [:index, :show]
  get 'tower/history/:id' => 'tower#history'
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :levels
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :check_admin, only: [:admin, :news_items]

  #The home page, with all the global stats
  def home
    if(logged_in?)
      @tower = Brick.all
      @news_items = current_user.news_items.order(created_at: :desc).paginate(page: params[:page], per_page: 20)
    end
  end

  def about
  end

  def admin
	@show_mode = session[:show]
  end

  #Page for the reporting problems
  def report
  	@error = NewsItem.new
  end

  #Handles posts to from problem reports, makes them into an update for the admins
  def submit
  	@message = NewsItem.new(error_params)
    #No shenagins, you hear!
    @message.message = ActionView::Base.full_sanitizer.sanitize(@message.message)
    #Gives this message to all admins
  	@message.users << User.where(admin: true)
  	@message.msg_type = "error_report"
  	if @message.save
  		flash[:success] = "Thank you for your report"
  		redirect_to '/'
  	else
  		flash[:danger] = "There was an error with the error reporting. That's just fucked up."
  		render 'report'
  	end
  end

  def show_mode
	session[:show] = !session[:show]
	redirect_to :admin
  end

  def news_items
        @news_items = NewsItem.order(created_at: :desc).paginate(page: params[:page], per_page: 10)
  end

  def actions
  end

  def strength
  end

  def gravity
  end

  def level
  end

  private
  	def error_params
  		params.require(:news_item).permit(:message)
  	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About TOWER TOWER TOWER") %>
<h1>What is Tower Tower Tower?</h1>
<p>
	Tower Tower Tower is a massively multiplayer game about building a tower up to the heavens. By stacking and combining bricks you can build the tower but the higher you get, the more challenges arise. And you've been cursed, so your only forms of communication are a limited set of glyphs. Work together over weeks and months with your fellow builders and maybe you'll be able to reach <span class = "overlap" data-text = "your reward">the heavens</span>.
</p>

<p>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/builders.png", title: 'BUILDERS', width: '40', class: 'glyph_image' %>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/up.png", title: 'UP', width: '40', class: 'glyph_image' %>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/both.png", title: 'BOTH', width: '40', class: 'glyph_image' %>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/left.png", title: 'LEFT', width: '40', class: 'glyph_image' %>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/both.png", title: 'BOTH', width: '40', class: 'glyph_image' %>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/right.png", title: 'right', width: '40', class: 'glyph_image' %>
</p>

<p>
	Tower Tower Tower is currently in open alpha, which means you can come and play but I may be
  changing things, adding new features, removing new features, deleting the entire tower, breaking
  everything, etc all the time. If you any feedback or encounter an error, don't hesitate to
  <a href = '/report'>report it.</a>
</p>

<h1>How do I play Tower Tower Tower?</h1>
<p>
	Click on <%= link_to "'Build Tower' or 'Play Now'", new_build_order_path%> to get started - there
  you can submit bricks to be added to the tower. More information about what will happen when you
  add to the tower can be found on the links below:<br>
	<ul>
		<li><a href = '/actions'>Actions</a></li>
		<li><a href = '/level'>Levels</a></li>
		<li><a href = '/strength'>Strength</a></li>
		<li><a href = '/gravity'>Gravity</a></li>
	</ul>
</p>

<h1>Where Did This Come From?</h1>
Tower Tower Tower was made by <a href = "http://thejhyde.zone">Julian Hyde</a>. Glyphs are from
<a href ="https://thenounproject.com">the Noun Project</a> and were made by shimaru, André Luiz Gollo, yugudesign.com, Vectors Market, To Uyen, Muneer A. Safiah, Alfredo Hernandez, Vishal Marotkar, Juan Pablo Bravo, Tina Rataj-Berard, Tahsin Tahil, Luis Prado, luism, Good Fridayss, Lloyd Humphreys, Hafzih, Mallory Hawes, Alexander Simone, Brian Dys Sahagun, stolkramaker, Mister Pixel, Jan-Christoph Borchardt, Jurjen Versteeg, Lia Jian Jie, Scott Lewis, and José Campos.

app/views/static_pages/actions.html.erb
<%= provide(:title, "Actions") %>

<h1 class = "center">What Are Actions?</h1>
<p>
	Every time you put bricks on the tower it costs one action. When you run out of actions, you can't
  place anymore bricks.
</p> 

<p>
	Actions are refreshed at noon EST every day: signed in players get 6 more actions and not signed in
  players get 2. If you don't use all your actions in a day they'll rollover to the next day
  but players cannot have more than 12 actions.
</p>

<p>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/bring.png", title: 'BRING', width: '40', class: 'glyph_image' %>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/AGAIN.png", title: 'AGAIN', width: '40', class: 'glyph_image' %>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/top.png", title: 'TOP', width: '40', class: 'glyph_image' %>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/column.png", title: 'COLUMN', width: '40', class: 'glyph_image' %>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/EDGE.png", title: 'EDGE', width: '40', class: 'glyph_image' %>
</p>

app/views/static_pages/admin.html.erb
<h1>Admin Page</h1>
I ain't making this look nice, nobody but us chickens in here<br/>
<%= link_to "All Users", users_path %><br/>
<%= link_to "All Build Orders", build_orders_path %><br/>
<%= link_to "All News Items", 'news_items' %><br/>
<%= link_to "Levels", levels_path %><br/>
<b>To Build</b><br/>
<%= link_to "All Bricks", '#' %><br/>

<p>
  <%= link_to "Show Mode", showmode_path %><br>
  The game is current
  <% if !@show_mode %>
    NOT
  <% end %>
  in show mode.
</p>

app/views/static_pages/gravity.html.erb
<%= provide(:title, "Falling") %>

<h1 class = "center">What is <span class = "overlap" data-text = "Falling">Gravity</span>?</h1>
<p>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/warning.png", title: 'WARNING', width: '40', class: 'glyph_image' %>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/down.png", title: 'DOWN', width: '40', class: 'glyph_image' %>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/destroy.png", title: 'DESTROY', width: '40', class: 'glyph_image' %>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/AGAIN.png", title: 'AGAIN', width: '40', class: 'glyph_image' %>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/AGAIN.png", title: 'AGAIN', width: '40', class: 'glyph_image' %>
</p>

<p>
	Bricks need support or they will fall and be destroyed. Destroyed by gravity. A brick is
  supported if there is brick underneath it, underneath to the left, or underneath to the
  right.
</p>

<p>
  <%= image_tag "#{Rails.configuration.x.img_url}gravity_diagram.png", class: 'centered' %>
</p>

<p>
	If a brick loses support at anytime, it will fall and be destroyed, even if it had been supported
  before.
</p>

<p>
  <span class = "overlap" data-text = "is what keeps us here Gravity">Gravity is what keeps us here</span>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "TOWER TOWER TOWER") %>
<% if !logged_in? %>
    <div class = "center jumbotron">
      <h1>TOWER TOWER TOWER</h1>
      <div id="canvas"></div>
      <p>
        Build the tower and escape to the heavens.
      </p>
      <p>
        <%= image_tag "#{Rails.configuration.x.img_url}glyphs/builders.png", title: 'BUILDERS', width: '40', class: 'glyph_image' %>
        <%= image_tag "#{Rails.configuration.x.img_url}glyphs/up.png", title: 'UP', width: '40', class: 'glyph_image' %>
        <%= image_tag "#{Rails.configuration.x.img_url}glyphs/no.png", title: 'NO', width: '40', class: 'glyph_image' %>
        <%= image_tag "#{Rails.configuration.x.img_url}glyphs/within.png", title: 'WITHIN', width: '40', class: 'glyph_image' %>
        <%= image_tag "#{Rails.configuration.x.img_url}glyphs/monster.png", title: 'MONSTER', width: '40', class: 'glyph_image' %>
      </p>
      <%= link_to "Play Now", new_build_order_path, class: "btn btn-primary" %>
      <%= link_to "About", about_path, class: "btn btn-primary" %>
      <%= link_to "Sign Up", signup_path, class: "btn btn-primary" %>
    </div>
<% else %>
    <h1><%= current_user.name %></h1>

    <p class = "center">
      <%= image_tag "#{Rails.configuration.x.img_url}glyphs/builders.png", title: 'BUILDERS', width: '40', class: 'glyph_image' %>
      <%= image_tag "#{Rails.configuration.x.img_url}glyphs/up.png", title: 'UP', width: '40', class: 'glyph_image' %>
      <%= image_tag "#{Rails.configuration.x.img_url}glyphs/no.png", title: 'NO', width: '40', class: 'glyph_image' %>
      <%= image_tag "#{Rails.configuration.x.img_url}glyphs/within.png", title: 'WITHIN', width: '40', class: 'glyph_image' %>
      <%= image_tag "#{Rails.configuration.x.img_url}glyphs/monster.png", title: 'MONSTER', width: '40', class: 'glyph_image' %>
    </p>

    <div id = "information">
      <div id = "stats" class = "stats_box">
        <strong>Personal Stats</strong><br>
        Actions: <%= current_user.actions %><br>
        Highest Level: <%= current_user.max_level - 1 %><br>
        <br>
        <strong>Global Stats</strong><br>
        Tower Height: <%= @tower.order(:y).last.y %> bricks, <%= @tower.order(:y).last.level.level %> levels</br>
        Total Bricks: <%= @tower.count %><br>
      </div>
      <div id = "canvas" class="stats_box"></div>
      <div id = "links" class = "stats_box">
        <%= link_to "Profile", current_user %><br/>
        <%= link_to "Settings", edit_user_path(current_user) %><br/>
        <%= link_to "Build Tower", new_build_order_path %><br/>
        <%= link_to "See Tower", tower_index_path %><br/>
        <% if current_user.admin %>
            <%= link_to 'Admin', '/admin' %>
        <% end %>
      </div>
    </div>

    <div id = "news_feed">
      <h3>News</h3>
      <ul>
        <% @news_items.each do |news| %>
            <li class = "<%= news.msg_type %>"><%= news.created_at.strftime("%_m/%-d, %l:%M %p")%>: <%= news.message.html_safe %></li>
        <% end %>
      </ul>
      <%= will_paginate @news_items %>
    </div>
<% end %>

app/views/static_pages/level.html.erb
<%= provide(:title, "Levels") %>

<h1 class = "center">What are Levels?</h1>
<p>
	The tower can be divided into distinct levels, each one on top of the other.
  <span class = "overlap" data-text = "You approach">Go ever higher</span>. Different levels
  have different rules: it might take more or less time for bricks to be placed, require more
  strength, or <span class = "overlap" data-text = "even worse things">things yet unknown</span>.
</p>

<p>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/up.png", title: 'UP', width: '40', class: 'glyph_image' %>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/destroy.png", title: 'DESTROY', width: '40', class: 'glyph_image' %>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/up.png", title: 'DESPAIR', width: '40', class: 'glyph_image' %>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/bring.png", title: 'BRING', width: '40', class: 'glyph_image' %>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/despair.png", title: 'DESPAIR', width: '40', class: 'glyph_image' %>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/up.png", title: 'STRENGTH', width: '40', class: 'glyph_image' %>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/large.png", title: 'LARGE', width: '40', class: 'glyph_image' %>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/monster.png", title: 'MONSTER', width: '40', class: 'glyph_image' %>
</p>

<p>
	Builders can only put bricks one level above the highest level they've successfully built on so far.If you've successfully put bricks on level 2, you can put bricks on level 3 but no higher. Levels above that can't be seen or built on.
</p>

<p>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/builder.png", title: 'BUILDER', width: '40', class: 'glyph_image' %>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/no.png", title: 'NO', width: '40', class: 'glyph_image' %>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/up.png", title: 'UP', width: '40', class: 'glyph_image' %>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/large.png", title: 'LARGE', width: '40', class: 'glyph_image' %>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/AGAIN.png", title: 'AGAIN', width: '40', class: 'glyph_image' %><br>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/bring.png", title: 'BRING', width: '40', class: 'glyph_image' %>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/within.png", title: 'WITHIN', width: '40', class: 'glyph_image' %>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/hole.png", title: 'HOLE', width: '40', class: 'glyph_image' %>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/top.png", title: 'TOP', width: '40', class: 'glyph_image' %>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/up.png", title: 'UP', width: '40', class: 'glyph_image' %>
</p>

app/views/static_pages/news_items.html.erb
<% provide(:title, "News Items") %>
<h1>News Items</h3>
<%= will_paginate @news_items %>
<ul>
	<% @news_items.each do |news| %>
		<li>
			<%= news.created_at.strftime("%_m/%-d, %l:%M %p")%>: <%= news.message.html_safe %><br/>
			<b>Type:</b>  <%= news.msg_type %><br/>
			<b>For:</b> <%= news.users.pluck(:name).to_sentence %>
		</li>
	<% end %>
</ul>
<%= will_paginate @news_items %>

app/views/static_pages/report.html.erb
<% provide(:title, "Report Errors") %>

<h1>Problems?</h1>
Please tell me about any problems you have. Please include your user name with the message.
<%= form_for(@error, url: '/submit') do |f| %>
	<%= f.label :message %><br/>
	<%= f.text_area :message, size: "20x10" %><br/>

	<%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/static_pages/strength.html.erb
<%= provide(:title, "Strength") %>

<h1 class = "center">What is Strength?</h1>
<p>
	Some bricks are stronger than others. Stronger bricks can survive at higher altitudes due to
  <span class="overlap" data-text = "blessings">stronger clay</span>.
</p>

<p>
	When you put a brick on top of a brick that matches it's color or put two bricks of the same color
  on the same place at the same time, you get a stronger brick. A brick's strength is shown in how many lines it has on it.
</p>

<p>
	When you put a brick on top of a brick of a different color or put two bricks of different colors on the tower at the same time, you get a weaker brick. If a brick's strength falls below zero, it is destroyed.
</p>

<p>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/STRENGTH.png", title: 'STRENGTH', width: '40', class: 'glyph_image' %>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/error.png", title: 'ERROR', width: '40', class: 'glyph_image' %>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/destroy.png", title: 'DESTROY', width: '40', class: 'glyph_image' %>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/REVERSE.png", title: 'REVERSE', width: '40', class: 'glyph_image' %>
  <%= image_tag "#{Rails.configuration.x.img_url}glyphs/top.png", title: 'TOP', width: '40', class: 'glyph_image' %>
</p>