config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'admin' => 'static_pages#admin'
  get 'report' => 'static_pages#report'
  post 'submit' => 'static_pages#submit'
  get 'news_items' => 'static_pages#news_items'
  get 'actions' => 'static_pages#actions'
  get 'strength' => 'static_pages#strength'
  get 'gravity' => 'static_pages#gravity'
  get 'level' => 'static_pages#level'
  get 'showmode' => 'static_pages#show_mode'


  get 'login' => 'sessions#new'
  get 'session' => 'sessions#index'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'signup' => 'users#new'
  resources :users
  get 'achievement_levels' => 'users#achievement_levels'

  resources :account_activations, only: [:edit]

  get 'build_orders/finished' => 'build_orders#finished'
  get 'build_orders/get_orders/:id' => 'build_orders#get_orders'
  resources :build_orders, only: [:new, :create, :index, :show]

  resources :tower, only: [:index, :show]
  get 'tower/history/:id' => 'tower#history'
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :levels
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user, only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]

  def new
  end

  def create
  	@user = User.find_by(email: params[:password_reset][:email].downcase)
  	if @user
  		@user.create_reset_digest
  		@user.send_password_reset_email
  		flash[:info] = "Email sent with password reset instructions"
  		redirect_to root_url
  	else
  		flash.now[:danger] = "Email address not found"
  		render 'new'
  	end
  end

  def edit
  end

  def update
  	if params[:user][:password].empty?
  		@user.errors.add(:password, "can't be empty")
  		render 'edit'
  	elsif @user.update_attributes(user_params)
  		log_in @user
  		flash[:success] = 'Password has been reset.'
  		redirect_to root_url
  	else
  		render 'edit'
  	end
  end

  private
  	def user_params
  		params.require(:user).permit(:password, :password_confirmation)
  	end

  	def get_user
  		@user = User.find_by(email: params[:email])
  	end

  	def valid_user
  		unless (@user && @user.activated? && @user.authenticated?(:reset, params[:id]))
  			redirect_to root_url
  		end
  	end

  	def check_expiration
  		if @user.password_reset_expired?
  			flash[:danger] = "Password reset has expired"
  			redirect_to new_password_reset_url
  		end
  	end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, "Reset Your Password") %>
<h1>Reset Password</h1>

<div class = "row">
	<div class = "col-md-6 col-md-offset-3">
		<%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
			<%= render 'shared/error_messages' %>
			
			<%= hidden_field_tag :email, @user.email %>

			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>

			<%= f.submit "Update Password", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, "Reset Password") %>
<h1>Forgot Password</h1>

<div class = "row">
	<div class = "col-md-6 col-md-offset-3">
		<%= form_for(:password_reset, url: password_resets_path) do |f| %>
			<%= f.label :email %>
			<%= f.email_field :email, class: 'form-control' %>

			<%= f.submit "Submit", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>