config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'admin' => 'static_pages#admin'
  get 'report' => 'static_pages#report'
  post 'submit' => 'static_pages#submit'
  get 'news_items' => 'static_pages#news_items'
  get 'actions' => 'static_pages#actions'
  get 'strength' => 'static_pages#strength'
  get 'gravity' => 'static_pages#gravity'
  get 'level' => 'static_pages#level'
  get 'showmode' => 'static_pages#show_mode'


  get 'login' => 'sessions#new'
  get 'session' => 'sessions#index'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'signup' => 'users#new'
  resources :users
  get 'achievement_levels' => 'users#achievement_levels'

  resources :account_activations, only: [:edit]

  get 'build_orders/finished' => 'build_orders#finished'
  get 'build_orders/get_orders/:id' => 'build_orders#get_orders'
  resources :build_orders, only: [:new, :create, :index, :show]

  resources :tower, only: [:index, :show]
  get 'tower/history/:id' => 'tower#history'
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :levels
end

app/models/level.rb
class Level < ActiveRecord::Base
  has_many :bricks
  has_many :build_orders
  has_many :stars
  validates :level, presence: true, uniqueness: true

  @default_text = 'Continue building the tower.|Your bricks will be added to the tower <nextTime()>.'

  def self.find_by_y(y)
    my_level = (y - 1)/10
    if Level.where(level: my_level).first.nil?
      Level.create(level: my_level,
                   update_rate: ((my_level+1)/2).round * 5,
                   strength_requirement: ((my_level+1)/3).round,
                   background: 'level_thirteen.jpg',
                   text: @default_text)
    else
      Level.where(level: my_level).first
    end
  end
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  before_action :check_admin, only: [:index, :new, :create, :edit, :update]

  def index
    @levels = Level.all
  end

  def new
    @level = Level.new
  end

  def create
    @level = Level.create(level_params)
    if @level.save
      redirect_to level_path
    else
      render 'new'
    end

  end

  def edit
    @level = Level.find(params[:id])
  end

  def update
    @level = Level.find(params[:id])
    if @level.update_attributes(level_params)
      flash[:success] = 'Updated level'
      redirect_to levels_path
    else
      render 'edit'
    end
  end

  def show
    this_level = Level.where(level: params[:id]).first
    @level = {}
    @level['level'] = this_level
    one_down = Brick.where(y: params["id"].to_i * Global.tower.level_height)
    one_up = Brick.where(y: (params["id"].to_i + 1) * Global.tower.level_height + 1);
    @level['bricks'] = this_level.bricks + one_down + one_up
    @level['stars'] = this_level.stars.where(found: false);
    respond_to do |format|
      format.json {render json: @level }
    end
  end

  private
    def level_params
      params.require(:level).permit(:level, :strength_requirement, :update_rate, :background, :text)
    end
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/views/levels/edit.html.erb
<% provide(:title, 'Edit Level') %>

<h1>Edit Level</h1>
<div>
  <%= form_for @level, url: "/levels/#{@level.id}" do |f| %>
      <%= f.label :level %><br>
      <%= f.text_field :level %><br>

      <%= f.label :update_rate %><br>
      <%= f.text_field :update_rate %><br>

      <%= f.label :strength_requirement %><br>
      <%= f.text_field :strength_requirement %><br>

      <%= f.label :background %><br>
      <%= f.text_field :background %><br>

      <%= f.label :text %><br>
      <%= f.text_area :text %><br>

      <%= f.submit 'Update' %>
  <% end %>
</div>

app/views/levels/index.html.erb
<h1>Levels</h1>

<hr>
<% @levels.order(:level).each do |level| %>
    <p>
      <%= level.level %>. Update Rate: <%= level.update_rate %>, Strength: <%= level.strength_requirement %>,
      Bricks: <%= level.bricks.count %> <a href = "/<%= level.background%>">Background</a>.
      <%= link_to 'Update', edit_level_path(level) %><br>
      <u>Text</u>: <%= level.text %>
    </p>
<% end %>

<%= link_to 'New Level', new_level_path %>

app/views/levels/new.html.erb
<% provide(:title, 'New Level') %>

<h1>New Level</h1>
<div>
  <div>
    <%= form_for @level do |f| %>
        <%= f.label :level %><br>
        <%= f.text_field :level %><br>

        <%= f.label :update_rate %><br>
        <%= f.text_field :update_rate %><br>

        <%= f.label :strength_requirement %><br>
        <%= f.text_field :strength_requirement %><br>

        <%= f.label :background %><br>
        <%= f.text_field :background %><br>

        <%= f.label :text %><br>
        <%= f.text_area :text %><br>

        <%= f.submit 'Create' %>
    <% end %>
  </div>
</div>