config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'admin' => 'static_pages#admin'
  get 'report' => 'static_pages#report'
  post 'submit' => 'static_pages#submit'
  get 'news_items' => 'static_pages#news_items'
  get 'actions' => 'static_pages#actions'
  get 'strength' => 'static_pages#strength'
  get 'gravity' => 'static_pages#gravity'
  get 'level' => 'static_pages#level'
  get 'showmode' => 'static_pages#show_mode'


  get 'login' => 'sessions#new'
  get 'session' => 'sessions#index'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'signup' => 'users#new'
  resources :users
  get 'achievement_levels' => 'users#achievement_levels'

  resources :account_activations, only: [:edit]

  get 'build_orders/finished' => 'build_orders#finished'
  get 'build_orders/get_orders/:id' => 'build_orders#get_orders'
  resources :build_orders, only: [:new, :create, :index, :show]

  resources :tower, only: [:index, :show]
  get 'tower/history/:id' => 'tower#history'
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :levels
end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
	<div class = "alert alert-<%=message_type%> box" >
    <p>
      <%= message.html_safe %> <a href="#" class="close">&times;</a>
    </p>
	</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class ="footer">
	<div id = "leftFooter">
		Tower Tower Tower is made by <a href="http://thejhyde.zone/">J. Hyde</a>
	</div>

	<div id = "rightFooter">
		<ul>
			<li><%= link_to "About", 	about_path %></li>
			<li><%= link_to "Report Problems", report_path %></li>
		</ul>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header>
	<ul>
		<li><%= link_to "Home", 	root_path %></li>
		<li><%= link_to "Actions", actions_path, target: '_blank'%>: <%= current_user.actions %></li>
		<li><%= link_to "About", 	about_path %></li>
    <% if current_user.actions > 0 %>
        <% if logged_in?%>
            <li><%= link_to "Build Tower", new_build_order_path %></li>
        <% else %>
            <li><%= link_to "Play Now", new_build_order_path %></li>
        <% end %>
    <% end %>
		<li><%= link_to "See Tower", tower_index_path %></li>
		<% if logged_in? %>
			<li><%= link_to "Log Out", logout_path, method: "delete" %></li>
		<% else %>
			<li><%= link_to "Sign Up", 	new_user_path %></li>
			<li><%= link_to "Log in", 	login_path %></li>
		<% end %>
	</ul>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= yield(:title) %></title>
	  <%= stylesheet_link_tag 'application' %>
	  <%= javascript_include_tag 'application' %>
	  <%= yield(:head) %>
	  <%= csrf_meta_tags %>
	  <%= render 'layouts/shim' %>
	</head>
	<body class = "<%= controller_name%> <%= action_name %>">
		<%= render 'layouts/header' %>
		<div class = "content">
			<%= render 'layouts/flash' %>
			<%= yield %>
		</div>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
		<%#= session.inspect if Rails.env.development? %>
	</body>
</html>